backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "source/assets/images" # Folder where user uploaded files should go
public_folder: "source"
